### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by helloafer** [TracyEminem/BleSingle#1]
感谢你把这个demo发出来，不知道有没有空写一下这个如何使用？我装到手机上，打开蓝牙设备，除了会有一个前台通知显示正在工作，就没有任何反映了。log中也看不到有任何变化，蓝牙设备是确定已经开启并可以用其它APP搜索到的。扫描配置里我也改成了自己蓝牙模块的名称。
     感觉应该是打开这个APP后，再打开蓝牙设备，应该有某些提示的。

**Comment by TracyEminem** [comment]
这个demo的作用是实现8.0以后的后台监测到特定蓝牙信号自动唤醒APP的功能，首先需要另外一个装了可以发射蓝牙信号软件的手机，我这边是选取的ios平台上的lightblue，然后在这个软件里面新建一个虚拟设备名称是要demo搜索的蓝牙模块名称。然后把app杀掉，过一段时间打开lightblue发射蓝牙信号，然后关掉，再次打开demo，会发现demo中记录的时间就是你发射蓝牙信号的时间，说明被杀后它还是在监测蓝牙信号的

**Comment by helloafer** [comment]
感谢回复，我需要的就是这样的功能。让android手机在后台监测我的蓝牙设备，能搜到时(比如从距离上接近时)可以让app被唤醒，APP再后台连接到这个蓝牙设备，和蓝牙设备交换一些数据，我的蓝牙设备就可以执行一些操作了。但目前我还没有试出效果来，demo中时间一直是:1970年，我再做些尝试吧。

**Comment by chentianci123** [comment]
> 感谢回复，我需要的就是这样的功能。让android手机在后台监测我的蓝牙设备，能搜到时(比如从距离上接近时)可以让app被唤醒，APP再后台连接到这个蓝牙设备，和蓝牙设备交换一些数据，我的蓝牙设备就可以执行一些操作了。但目前我还没有试出效果来，demo中时间一直是:1970年，我再做些尝试吧。

请问一下，您现在已经实现你的功能了吗
