### ISSUE TITLE
使用后台服务，唤醒失败

### ISSUE THREAD

**Issue by shaotian** [TracyEminem/BleSingle#2]
考虑这种场景，做无感知保活。必须使用后台服务来做，当App被杀后，进程是唤不起来的，因为8.0对后台进程做了很多限制，AMS日志会是这样的
ActivityManager: Background start not allowed: service Intent { act=com.hungrytree.receiver.BleService pkg=com.example.tracyeminem.blesingle (has extras) } to com.example.tracyeminem.blesingle/.TestService from pid=-1 uid=10296 pkg=com.example.tracyeminem.blesingle

**Comment by shaotian** [comment]
ActivityManager: Background start not allowed: service Intent { act=com.hungrytree.receiver.BleService pkg=com.example.tracyeminem.blesingle (has extras) } to com.example.tracyeminem.blesingle/.TestService from pid=-1 uid=10296 pkg=com.example.tracyeminem.blesingle

**Comment by shaotian** [comment]
8.0以后限制：https://developer.android.com/about/versions/oreo/background.html

还有 用了下Android 9.0的MIUI10 即使前台服务，App杀掉后也无法通过这种方式唤醒

**Comment by shaotian** [comment]
还有 用了下Android 9.0的MIUI10 即使前台服务，App杀掉后也无法通过这种方式唤醒

**Comment by TracyEminem** [comment]
你指的后台服务是workmanager吗？workmanager的运行时机是无法预知的，只有在满足条件的情况下才可能启动。。。你使用的是8.0的手机吗？我测试的2台手机都是8.0的，都没有问题。。。但是有可能是我手动开启了权限，我明天再试一下

**Comment by TracyEminem** [comment]
看了一下，进程是没有唤醒，但是这个检测蓝牙的service会被唤醒，service里面可以执行一些逻辑。
