### ISSUE TITLE
你好，这个demo安装后具体怎么操作？

### ISSUE THREAD

**Issue by chentianci123** [TracyEminem/BleSingle#3]
我下载了lightBlue，也创建一个叫test2的虚拟设备，但是下载lightblue的手机好像和安装demo的手机没有什么关联，我这边模拟你那篇文章的操作，结果没有反应，请问怎么解决

**Comment by TracyEminem** [comment]
如果是需要保活的话请使用这个库 https://github.com/ShihooWang/DaemonLibrary

**Comment by chentianci123** [comment]
> 如果是需要保活的话请使用这个库 https://github.com/ShihooWang/DaemonLibrary

我想要使用蓝牙信号拉活app，但是这个demo不知道怎么照着你的操作进行，我是第一次开发android，对蓝牙操作更是不了解

**Comment by chentianci123** [comment]
> 如果是需要保活的话请使用这个库 https://github.com/ShihooWang/DaemonLibrary

是不是需要让那个虚拟设备连接到我安装demo的蓝牙上面，https://blog.csdn.net/qq_16624353/article/details/85260778这个连接的gif操作

**Comment by TracyEminem** [comment]
不需要连接，我不知道你的问题出在哪里，首先你得确保lightblue正确的发出了test2为名字的广播包，如果APP检测到蓝牙信号，主页的时间会变成最近搜到蓝牙信号的时间，大概是这样。

**Comment by chentianci123** [comment]
> 不需要连接，我不知道你的问题出在哪里，首先你得确保lightblue正确的发出了test2为名字的广播包，如果APP检测到蓝牙信号，主页的时间会变成最近搜到蓝牙信号的时间，大概是这样。

非常感谢，那个test2广播包是不是需要连一个services，这个services是随便连还是怎么做

**Comment by chentianci123** [comment]
> 不需要连接，我不知道你的问题出在哪里，首先你得确保lightblue正确的发出了test2为名字的广播包，如果APP检测到蓝牙信号，主页的时间会变成最近搜到蓝牙信号的时间，大概是这样。

如果没有连接services的话是无法发送广播的

**Comment by TracyEminem** [comment]
不需要连接啊，service除了要是前台service没有特殊要求，只是在service里面做接收到扫描结果的工作。连接也是activity和service的连接，和蓝牙没啥关系啊

**Comment by chentianci123** [comment]
> 不需要连接啊，service除了要是前台service没有特殊要求，只是在service里面做接收到扫描结果的工作。连接也是activity和service的连接，和蓝牙没啥关系啊

我可以加你个微信吗，我好像描述不清楚我的问题，我用手机把截图发给你

**Comment by chentianci123** [comment]
> 不需要连接啊，service除了要是前台service没有特殊要求，只是在service里面做接收到扫描结果的工作。连接也是activity和service的连接，和蓝牙没啥关系啊

这个demo是不是对有些华为型号不兼容，我发送广播，然后那个时间并没有变化

**Comment by TracyEminem** [comment]
不是，时间的变化需要你重新进入activity才能看到，不是立马直接变化的，你可以看下里面的代码，总共就一点点。但是这个库可能无法满足你需要的拉活进程的需求，因为这个只能拉活service，能不能通过service拉活app进程得你自己去研究了。

**Comment by chentianci123** [comment]
> 不是，时间的变化需要你重新进入activity才能看到，不是立马直接变化的，你可以看下里面的代码，总共就一点点。但是这个库可能无法满足你需要的拉活进程的需求，因为这个只能拉活service，能不能通过service拉活app进程得你自己去研究了。

奥奥，我看你是在activity里面onResume这个生命周期里设置的时间，应该是我退出应用后发送广播，然后demo接收到信号后他的应用图标会在手机显示，这就证明demo被拉活了，然后打开后时间变了，但是我现在发送广播后他并没有被拉活，所以时间也没有变，是不是我理解错意思了

**Comment by TracyEminem** [comment]
你没有理解错，可能是你的app没有获取到蓝牙扫描和定位的权限，你排查一下

**Comment by chentianci123** [comment]
> 你没有理解错，可能是你的app没有获取到蓝牙扫描和定位的权限，你排查一下

我刚看了看，蓝牙权限和位置权限都有的，我在想是不是安卓版本问题或者手机型号问题，因为我换了好几个型号的手机，他们有的装上闪退，有的装上了发送广播后没有反应，对了，你之前给我发的那个连接是不是也可以拉活service，还是他可以保证应用在后台时进程不被杀死

**Comment by TracyEminem** [comment]
我不知道你们遇到了什么问题，我在几台手机上测试过都没有问题，之前发的那个连接是保活的，app会一直在后台运行，和蓝牙没什么关系，你可以在他的workservice里面配置蓝牙扫描的功能，或者是再workservice里面使用我这个library里面的哪个带intentfilter的蓝牙扫描方法就可以了。

**Comment by chentianci123** [comment]
> 我不知道你们遇到了什么问题，我在几台手机上测试过都没有问题，之前发的那个连接是保活的，app会一直在后台运行，和蓝牙没什么关系，你可以在他的workservice里面配置蓝牙扫描的功能，或者是再workservice里面使用我这个library里面的哪个带intentfilter的蓝牙扫描方法就可以了。

行吧，那我感觉就是我使用lightblue的问题，https://www.jianshu.com/p/2bfde2ba8a99我找了个教程，他说需要连接设备，但是我并不知道我的设备的名称，lightblue不显示名称

**Comment by chentianci123** [comment]
> 我不知道你们遇到了什么问题，我在几台手机上测试过都没有问题，之前发的那个连接是保活的，app会一直在后台运行，和蓝牙没什么关系，你可以在他的workservice里面配置蓝牙扫描的功能，或者是再workservice里面使用我这个library里面的哪个带intentfilter的蓝牙扫描方法就可以了。

你在测试的时候使用lightblue连接设备了吗

**Comment by chentianci123** [comment]
> > 我不知道你们遇到了什么问题，我在几台手机上测试过都没有问题，之前发的那个连接是保活的，app会一直在后台运行，和蓝牙没什么关系，你可以在他的workservice里面配置蓝牙扫描的功能，或者是再workservice里面使用我这个library里面的哪个带intentfilter的蓝牙扫描方法就可以了。
> 
> 行吧，那我感觉就是我使用lightblue的问题，[https://www.jianshu.com/p/2bfde2ba8a99我找了个教程，他说需要连接设备，但是我并不知道我的设备的名称，lightblue不显示名称](https://www.jianshu.com/p/2bfde2ba8a99%E6%88%91%E6%89%BE%E4%BA%86%E4%B8%AA%E6%95%99%E7%A8%8B%EF%BC%8C%E4%BB%96%E8%AF%B4%E9%9C%80%E8%A6%81%E8%BF%9E%E6%8E%A5%E8%AE%BE%E5%A4%87%EF%BC%8C%E4%BD%86%E6%98%AF%E6%88%91%E5%B9%B6%E4%B8%8D%E7%9F%A5%E9%81%93%E6%88%91%E7%9A%84%E8%AE%BE%E5%A4%87%E7%9A%84%E5%90%8D%E7%A7%B0%EF%BC%8Clightblue%E4%B8%8D%E6%98%BE%E7%A4%BA%E5%90%8D%E7%A7%B0)

![微信图片_20191129140419](https://user-images.githubusercontent.com/49859313/69847173-56068280-12b1-11ea-81e5-937799e5a9bd.jpg)
![微信图片_20191129140424](https://user-images.githubusercontent.com/49859313/69847178-599a0980-12b1-11ea-8aaa-7b3edaa3c6b1.jpg)

这是我使用lightblue的广播配置，我把你的demo代码中的test2改为test了，所以我创建的是test

**Comment by chentianci123** [comment]
> > > 我不知道你们遇到了什么问题，我在几台手机上测试过都没有问题，之前发的那个连接是保活的，app会一直在后台运行，和蓝牙没什么关系，你可以在他的workservice里面配置蓝牙扫描的功能，或者是再workservice里面使用我这个library里面的哪个带intentfilter的蓝牙扫描方法就可以了。
> > 
> > 
> > 行吧，那我感觉就是我使用lightblue的问题，[https://www.jianshu.com/p/2bfde2ba8a99我找了个教程，他说需要连接设备，但是我并不知道我的设备的名称，lightblue不显示名称](https://www.jianshu.com/p/2bfde2ba8a99%E6%88%91%E6%89%BE%E4%BA%86%E4%B8%AA%E6%95%99%E7%A8%8B%EF%BC%8C%E4%BB%96%E8%AF%B4%E9%9C%80%E8%A6%81%E8%BF%9E%E6%8E%A5%E8%AE%BE%E5%A4%87%EF%BC%8C%E4%BD%86%E6%98%AF%E6%88%91%E5%B9%B6%E4%B8%8D%E7%9F%A5%E9%81%93%E6%88%91%E7%9A%84%E8%AE%BE%E5%A4%87%E7%9A%84%E5%90%8D%E7%A7%B0%EF%BC%8Clightblue%E4%B8%8D%E6%98%BE%E7%A4%BA%E5%90%8D%E7%A7%B0)
> 
> ![微信图片_20191129140419](https://user-images.githubusercontent.com/49859313/69847173-56068280-12b1-11ea-81e5-937799e5a9bd.jpg)
> ![微信图片_20191129140424](https://user-images.githubusercontent.com/49859313/69847178-599a0980-12b1-11ea-8aaa-7b3edaa3c6b1.jpg)
> 
> 这是我使用lightblue的广播配置，我把你的demo代码中的test2改为test了，所以我创建的是test

请问一下，在AndroidMainFest中注册的com.hungrytree.receiver.BleService是什么意思，没太搞明白

**Comment by chentianci123** [comment]
> 我不知道你们遇到了什么问题，我在几台手机上测试过都没有问题，之前发的那个连接是保活的，app会一直在后台运行，和蓝牙没什么关系，你可以在他的workservice里面配置蓝牙扫描的功能，或者是再workservice里面使用我这个library里面的哪个带intentfilter的蓝牙扫描方法就可以了。

非常感谢，我现在在android8和android9上都实现了，但是在android10上没有响应，我不知道是权限问题还是什么，请问您有没有遇到类似的问题

**Comment by TracyEminem** [comment]
我没有测试过Android10，具体是什么问题我也不知道，可能是后台的某些权限吧，可以把运行后台运行打开试试。

**Comment by chentianci123** [comment]
> 可能是后台的某些权限吧，可以把运行后台运行打开试试。

非常感谢你的回答，我不太明白你的意思，后台运行打开可以测试权限问题吗，如果是我应该怎么测

**Comment by chentianci123** [comment]
我的问题彻底解决了，是因为mate30的GPS定位未打开

**Comment by TracyEminem** [comment]
你是解决了你自己的项目需求吗？还是只是在各个版本上跑通了这个demo呢？

**Comment by chentianci123** [comment]
> 你是解决了你自己的项目需求吗？还是只是在各个版本上跑通了这个demo呢？

在各版本跑通了这个demo
